name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  build_angular_project:
    name: Build angular project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node 15.14.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.14.x'
      - name: Install dependencies
        run: npm i
      - name: Build angular resources
        run: npm run build:prod
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: /FriendsAndPlaces/dist/
  build_docker_image:
    needs: build_angular_project
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: FriendsAndPlaces/
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: FAP-Cloud-Service/frontend
          tag_with_ref: true
