name: Publish Docker image
on:
  push:
    branches: 
      - develop
jobs:
  build_angular_project:
    name: Build angular project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FriendsAndPlaces
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node 15.14.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.14.x'
      - name: Setup angular cli
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: npm install
      - name: Build angular resources
        run:  npm run build:prod
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: FriendsAndPlaces/dist/
  build_docker_image:
    needs: build_angular_project
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist/
      - name: "[DEBUG] Show Folder Structure"
        run: ls -l && cd FriendsAndPlaces && ls -l && cd dist && ls -l
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login docker.pkg.github.com -u leonschbbht --password-stdin
      - name: Build Docker image
        run: docker build ./ --tag docker.pkg.github.com/FAP-Cloud-Service/frontend
      - name: Push to GitHub Packages Container Registry
        run: docker push docker.pkg.github.com/FAP-Cloud-Service/frontend
